apiVersion: v1
kind: Pod
metadata:
  name: mywebippod
  labels: 
    app: mywebip_lbl
  namespace: default
spec:
  containers:
    - name: mywebipcntr
      image: dockermano1984/whatismyip:v1
      ports:
        - containerPort: 5000